### PR TITLE
Fix issue #109

### LINKED ISSUE #109: Replace dummy values displayed in SummaryWindow.

### PR DESCRIPTION
**Pull request by HolmesJJ**
Close #109

### CODE REVIEW

File: src/main/java/seedu/address/logic/Logic.java [hunk 1]
```diff
@@ -45,56 +44,6 @@
...
-     */
-    double getTotalAmountOfTransactionsPastThreeMonth();
-
-    /**
-     * Returns the total amount of transactions in the past 6 months in ezFoodie.
-     */
-    double getTotalAmountOfTransactionsPastSixMonth();
-
     /**
      * Returns the user prefs' ezFoodie file path.
```
Comment (Morrow1ndy) [inline src/main/java/seedu/address/logic/Logic.java:48]: Good choice not to use HashMap.

File: src/main/java/seedu/address/model/reservation/Reservation.java [hunk 2]
```diff
@@ -14,7 +14,8 @@
  */
 public class Reservation {
 
-    public static final String MESSAGE_CONSTRAINTS = "The given reservation data time should be one day after today.";
+    public static final String MESSAGE_CONSTRAINTS =
+            "The given reservation data time should be after current date time.";
```
Comment (Morrow1ndy) [inline src/main/java/seedu/address/model/reservation/Reservation.java:18]: Good to include time also.

File: src/main/java/seedu/address/ui/SummaryCard.java [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+        // instanceof handles nulls
+        if (!(other instanceof SummaryCard)) {
+            return false;
+        }
+
+        // state check
+        SummaryCard card = (SummaryCard) other;
+        return memberList.equals(card.memberList);
+    }
+}
```
Comment (Morrow1ndy) [inline src/main/java/seedu/address/ui/SummaryCard.java:110]: Nice to separate it out to a card.

File: src/main/resources/view/SummaryWindow.fxml [hunk 4]
```diff
@@ -3,47 +3,29 @@
...
-    </scene>
+      <VBox>
+        <StackPane VBox.vgrow="NEVER" fx:id="summaryCardPlaceholder" styleClass="pane-with-border">
+          <padding>
+            <Insets top="5" right="10" bottom="5" left="10" />
+          </padding>
+        </StackPane>
+      </VBox>
+    </Scene>
+  </scene>
```
Comment (Morrow1ndy) [inline src/main/resources/view/SummaryWindow.fxml:30]: Good change to UI.

**Review by Morrow1ndy — COMMENTED** [review]
LGTM
